### ISSUE TITLE
Auto accept the connection pop-up [8h]

### ISSUE THREAD

**Issue by sladomic** [literacyapp-org/literacyapp-synchronization#5]
https://github.com/mdabbagh88/alljoyn_java/blob/master/helper/org/alljoyn/bus/p2p/WifiDirectAutoAccept.java

http://stackoverflow.com/a/18629705/7388005

**Comment by elich11** [comment]
Working on it

**Comment by elich11** [comment]
Done.

**Comment by elich11** [comment]
Done.
